/home/lappet/anaconda/bin/python matrix.py 0.5 > mu--05.log
/home/lappet/anaconda/bin/python matrix.py 0.6 > mu--06.log
/home/lappet/anaconda/bin/python matrix.py 0.7 > mu--07.log
/home/lappet/anaconda/bin/python matrix.py 0.8 > mu--08.log
/home/lappet/anaconda/bin/python matrix.py 0.5 > mu_-05.log
/home/lappet/anaconda/bin/python matrix.py 0.6 > mu_-06.log
/home/lappet/anaconda/bin/python matrix.py 0.7 > mu_-07.log
/home/lappet/anaconda/bin/python matrix.py 0.8 > mu_-08.log
/home/lappet/anaconda/bin/python matrix.py 0.5 > mu-_05.log
/home/lappet/anaconda/bin/python matrix.py 0.6 > mu-_06.log
/home/lappet/anaconda/bin/python matrix.py 0.7 > mu-_07.log
/home/lappet/anaconda/bin/python matrix.py 0.8 > mu-_08.log
/home/lappet/anaconda/bin/python matrix.py 0.5 > mu__05.log
/home/lappet/anaconda/bin/python matrix.py 0.6 > mu__06.log
/home/lappet/anaconda/bin/python matrix.py 0.7 > mu__07.log
/home/lappet/anaconda/bin/python matrix.py 0.8 > mu__08.log
/home/lappet/anaconda/bin/python matrix.py 0.5 > _mu__05.log
/home/lappet/anaconda/bin/python matrix.py 0.6 > _mu__06.log
/home/lappet/anaconda/bin/python matrix.py 0.7 > _mu__07.log
/home/lappet/anaconda/bin/python matrix.py 0.8 > _mu__08.log
