/home/lappet/anaconda/bin/python matrix.py 1.3 > mu-_13.log
/home/lappet/anaconda/bin/python matrix.py 1.4 > mu-_14.log
/home/lappet/anaconda/bin/python matrix.py 1.5 > mu-_15.log
/home/lappet/anaconda/bin/python matrix.py 2.0 > mu-_20.log
/home/lappet/anaconda/bin/python matrix.py 2.5 > mu-_25.log
/home/lappet/anaconda/bin/python matrix.py 1.3 > mu_-13.log
/home/lappet/anaconda/bin/python matrix.py 1.4 > mu_-14.log
/home/lappet/anaconda/bin/python matrix.py 1.5 > mu_-15.log
/home/lappet/anaconda/bin/python matrix.py 2.0 > mu_-20.log
/home/lappet/anaconda/bin/python matrix.py 2.5 > mu_-25.log
/home/lappet/anaconda/bin/python matrix.py 1.3 > mu--13.log
/home/lappet/anaconda/bin/python matrix.py 1.4 > mu--14.log
/home/lappet/anaconda/bin/python matrix.py 1.5 > mu--15.log
/home/lappet/anaconda/bin/python matrix.py 2.0 > mu--20.log
/home/lappet/anaconda/bin/python matrix.py 2.5 > mu--25.log
/home/lappet/anaconda/bin/python matrix.py 1.3 > mu__13.log
/home/lappet/anaconda/bin/python matrix.py 1.4 > mu__14.log
/home/lappet/anaconda/bin/python matrix.py 1.5 > mu__15.log
/home/lappet/anaconda/bin/python matrix.py 2.0 > mu__20.log
/home/lappet/anaconda/bin/python matrix.py 2.5 > mu__25.log
/home/lappet/anaconda/bin/python matrix.py 1.3 > _mu__13.log
/home/lappet/anaconda/bin/python matrix.py 1.4 > _mu__14.log
/home/lappet/anaconda/bin/python matrix.py 1.5 > _mu__15.log
/home/lappet/anaconda/bin/python matrix.py 2.0 > _mu__20.log
/home/lappet/anaconda/bin/python matrix.py 2.5 > _mu__25.log
